name: Update GeoJSON from Google Sheet

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Convert CSV to GeoJSON
        run: |
          python convert.py

      - name: Commit GeoJSON
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data.geojson
          git commit -m "Update GeoJSON" || echo "No changes"
          git push
