name: Sync Google Sheet to GeoJSON

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"  # Runs daily at 01:00 UTC

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas geojson

      - name: Download CSV from Google Sheets and convert to GeoJSON
        run: |
          mkdir -p output
          curl -L "https://docs.google.com/spreadsheets/d/1z8Xg20thWKyh-LyG04MLjnKzuCgFFgdsepIvMpqOGP8/export?format=csv&gid=0" -o data.csv
          
          python <<EOF
import pandas as pd, geojson, json

df = pd.read_csv("data.csv")

features = []
for _, row in df.iterrows():
    try:
        geom = json.loads(row["geometry"])  # assumes 'geometry' column in GeoJSON format
        feat = geojson.Feature(geometry
