name: Sync GeoJSON from Google Sheets

on:
  push:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run convert.py to update GeoJSON
        run: python convert.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.geojson
          git diff --cached --quiet || git commit -m "🔄 Update data.geojson from Google Sheets"
          git push
